# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0002_auto_20170501_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('task_date', models.DateTimeField(auto_now=True)),
                ('task_time', models.DateTimeField(auto_now=True)),
                ('task_status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertasks', to='login_app.User')),
            ],
        ),
    ]
