# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity_falls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
