# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 05:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gravity_falls', '0002_auto_20170502_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_user',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
