# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 05:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gravity_falls', '0003_auto_20170502_0043'),
        ('login_app', '0002_auto_20170501_2255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
